### ISSUE TITLE
I cannot download train/val/test json files

### ISSUE THREAD

**Issue by bozhenhhu** [eric-xw/Video-guided-Machine-Translation#8]
when I executed ./data/download.sh , I got the error failed:connection refused, and I cannot open the  link https://vatex.org/, maybe this website has been invalid.
I do not know the effects of these json files if I don't have them, could you give me the new links or these json files directly?
Thank you very much

**Comment by eric-xw** [comment]
thanks for the note. I have fixed the bash file. The correct link should be https://eric-xw.github.io/vatex-website now.
