### ISSUE TITLE
Website is not accessible

### ISSUE THREAD

**Issue by RyanLiut** [eric-xw/Video-guided-Machine-Translation#9]
Hi, seemly the website: https://eric-xw.github.io/vatex-website/download.html can't open?

**Comment by bozhenhhu** [comment]
wget https://eric-xw.github.io/vatex-website/data/vatex_training_v1.0.json -P data/
wget https://eric-xw.github.io/vatex-website/data/vatex_validation_v1.0.json -P data/
wget https://eric-xw.github.io/vatex-website/data/vatex_public_test_english_v1.1.json -P data/
I use this and succeed

**Comment by eric-xw** [comment]
The website is working well.
